# secrets required:
# DOCKERHUB_USERNAME
# DOCKERHUB_TOKEN
# DOCKERHUB_REPOSITORY

name: Release Docker build
run-name: Build and push update image
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
     
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Setup .NET Core SDK 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Load cached dependencies
        uses: actions/cache@v4.0.2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Install dependencies
        run: dotnet restore --locked-mode 

      - name: Publish 
        run: dotnet publish Docker.Net -c Release -p:PublishSingleFile=true -o bin/Docker.Net --no-restore
      
      - name: Build and push update image
        uses: docker/build-push-action@v6
        with:
          file: ./Docker.Net/Dockerfile
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:latest 

     